services:
  - type: web
    name: mybuilder
    runtime: node
    rootDir: server
    buildCommand: npm install && cd ../client && npm install && npx ng build --configuration production
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 3000
